name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Readme with WakaTime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      - name: Commit and push changes
        run: |
          git config user.name "Automated Workflow"
          git config user.email "actions@github.com"
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update Readme with WakaTime metrics"
            git push
          else
            echo "No changes detected. Skipping commit and push."
          fi
