name: Latest Tweets

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        github-token: ${{ github.token }}
        
    - name: Update Readme with Latest Tweets
      uses: jamesgeorge007/github-activity-readme@master
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        GH_USERNAME: mohitmishra786
        COMMIT_NAME: github-actions[bot]
        COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
        COMMIT_MSG: ':zap: Update README with the recent activity'
        MAX_LINES: 5
        TARGET_FILE: README.md
        EMPTY_COMMIT_MSG: ':memo: empty commit to keep workflow active after 60 days of no activity'
        
    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update latest tweets'
        branch: main
