name: Latest Tweets

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Pull in Latest Tweets
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWEETS"
          feed_list: "https://nitter.net/chessMan786/rss"
          max_post_count: 5
          template: "[$title]($url)"
          
      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update latest tweets'
          branch: main
