name: Latest Tweets

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update Readme with Latest Tweets
      uses: jamesgeorge007/github-activity-readme@master
      with:
        GITHUB_TOKEN: ${{ github.token }}
        TWITTER_USERNAME: 'your_twitter_username'
        COMMIT_MESSAGE: 'Update README with latest tweets'
        MAX_LINES: 5
        COMMIT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
        COMMIT_NAME: 'github-actions[bot]'
        
    - name: Commit and Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update latest tweets'
        branch: main
